//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioServer.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerTable
    {
        public int id { get; set; }
        public int ComputerNumber { get; set; }
        public string ComputerIP { get; set; }
        public Nullable<int> VerticalCoordinates { get; set; }
        public Nullable<int> HorizontalCoordinates { get; set; }
    }
}
